DELIMITER //

CREATE FUNCTION PROJ.FN_GET_COMMON_CD_NAME (COMM_CD VARCHAR(50), COMM_CD_VAL VARCHAR(50)) 
RETURNS VARCHAR(50) 
DETERMINISTIC
BEGIN 
    DECLARE v_cd_name VARCHAR(50); 
    
    SELECT COMMON_CD_NAME 
    INTO v_cd_name 
    FROM PROJ.TB_COMMON_CODE 
    WHERE 
        COMMON_CD = COMM_CD
        AND COMMON_CD_VAL = COMM_CD_VAL; 

    RETURN v_cd_name; 
END; //

DELIMITER ;
