CREATE OR REPLACE FUNCTION FN_GET_COMMON_CD_NAME (COMM_CD VARCHAR2, COMM_CD_VAL VARCHAR2) 
    RETURN VARCHAR2 
IS 
    v_cd_name VARCHAR2(50); 
BEGIN 
    SELECT COMMON_CD_NAME 
        INTO v_cd_name 
    FROM TB_COMMON_CODE 
    WHERE 
        COMMON_CD = COMM_CD
        AND COMMON_CD_VAL = COMM_CD_VAL; 

    RETURN v_cd_name; 
END;