const STAGES = [
    {
        id: "stage-01",
        name: "Stage 01 - Switch Door",
        description: "Clone이 스위치를 누르는 동안 문을 통과해 탈출하세요.",
        rows: 5,
        cols: 7,
        maxActions: 14,
        start: { row: 2, col: 0 },
        switches: [
            { group: "A", type: "hold", row: 0, col: 2 },
        ],
        doors: [
            { group: "A", row: 2, col: 3 },
        ],
        exit: { row: 2, col: 6 },
        walls: [
            { row: 0, col: 3 },
            { row: 1, col: 3 },
            { row: 3, col: 3 },
            { row: 4, col: 3 },
        ],
    },
    {
        id: "stage-02",
        name: "Stage 02 - Waiting Timing",
        description: "Clone의 스위치 타이밍에 맞춰 대기 후 문을 통과하세요.",
        rows: 5,
        cols: 8,
        maxActions: 16,
        start: { row: 2, col: 0 },
        switches: [
            { group: "A", type: "hold", row: 4, col: 2 },
        ],
        doors: [
            { group: "A", row: 2, col: 4 },
        ],
        exit: { row: 2, col: 7 },
        walls: [
            { row: 0, col: 4 },
            { row: 1, col: 4 },
            { row: 3, col: 4 },
            { row: 4, col: 4 },
            { row: 1, col: 2 },
            { row: 2, col: 2 },
        ],
    },
    {
        id: "stage-03",
        name: "Stage 03 - Multiple Switches",
        description: "여러 스위치를 눌러 모든 문을 열고 출구로 이동하세요.",
        rows: 6,
        cols: 8,
        maxActions: 18,
        start: { row: 2, col: 0 },
        switches: [
            { group: "A", type: "hold", row: 2, col: 2 },
            { group: "B", type: "hold", row: 4, col: 3 },
        ],
        doors: [
            { group: "A", row: 2, col: 4 },
            { group: "B", row: 3, col: 6 },
        ],
        exit: { row: 3, col: 7 },
        walls: [
            { row: 0, col: 4 },
            { row: 1, col: 4 },
            { row: 3, col: 4 },
            { row: 4, col: 4 },
            { row: 5, col: 4 },
            { row: 2, col: 6 },
            { row: 2, col: 7 },
            { row: 4, col: 6 },
            { row: 4, col: 7 },
        ],
    },
    {
        id: "stage-04",
        name: "Stage 04 - Multiple Switches",
        description: "여러 스위치를 눌러 모든 문을 열고 출구로 이동하세요.",
        rows: 6,
        cols: 8,
        maxActions: 16,
        start: { row: 2, col: 0 },
        switches: [
            { group: "A", type: "once", row: 2, col: 2 },
            { group: "B", type: "hold", row: 1, col: 5 },
        ],
        doors: [
            { group: "A", row: 2, col: 4 },
            { group: "B", row: 3, col: 6 },
        ],
        exit: { row: 3, col: 7 },
        walls: [
            { row: 0, col: 4 },
            { row: 1, col: 4 },
            { row: 3, col: 4 },
            { row: 4, col: 4 },
            { row: 5, col: 4 },
            { row: 2, col: 6 },
            { row: 2, col: 7 },
            { row: 4, col: 6 },
            { row: 4, col: 7 },
        ],
    },
    {
        id: "stage-05",
        name: "Stage 05 - Split Route Timing",
        description: "여러 스위치를 눌러 모든 문을 열고 출구로 이동하세요.",
        rows: 7,
        cols: 10,
        maxActions: 34,
        start: { row: 4, col: 0 },
        switches: [
            { group: "A", type: "once", row: 1, col: 3 },
            { group: "B", type: "hold", row: 1, col: 6 },
        ],
        doors: [
            { group: "A", row: 4, col: 3 },
            { group: "B", row: 2, col: 8 },
        ],
        exit: { row: 2, col: 9 },
        walls: [
            { row: 1, col: 1 },
            { row: 3, col: 2 },
            { row: 4, col: 2 },
            { row: 5, col: 2 },
            { row: 6, col: 2 },
            { row: 0, col: 4 },
            { row: 1, col: 4 },
            { row: 2, col: 4 },
            { row: 3, col: 4 },
            { row: 5, col: 4 },
            { row: 0, col: 5 },
            { row: 0, col: 6 },
            { row: 2, col: 6 },
            { row: 4, col: 6 },
            { row: 5, col: 6 },
            { row: 6, col: 6 },
            { row: 0, col: 7 },
            { row: 1, col: 7 },
            { row: 1, col: 8 },
            { row: 3, col: 8 },
            { row: 1, col: 9 },
            { row: 3, col: 9 },
        ],
    },
    {
        id: "stage-06",
        name: "Stage 06 - Split Route Timing",
        description: "여러 스위치를 눌러 모든 문을 열고 출구로 이동하세요.",
        rows: 6,
        cols: 8,
        maxActions: 33,
        start: { row: 4, col: 0 },
        switches: [
            { group: "A", type: "once", row: 1, col: 1 },
            { group: "B", type: "hold", row: 5, col: 3 },
            { group: "C", type: "hold", row: 3, col: 4 },
        ],
        doors: [
            { group: "A", row: 2, col: 2 },
            { group: "B", row: 2, col: 5 },
            { group: "C", row: 3, col: 6 },
        ],
        exit: { row: 4, col: 7 },
        walls: [
            { row: 0, col: 2 },
            { row: 1, col: 2 },
            { row: 3, col: 2 },
            { row: 4, col: 2 },
            { row: 5, col: 2 },
            { row: 0, col: 3 },
            { row: 1, col: 3 },
            { row: 0, col: 4 },
            { row: 4, col: 4 },
            { row: 5, col: 4 },
            { row: 0, col: 5 },
            { row: 1, col: 5 },
            { row: 3, col: 5 },
            { row: 4, col: 5 },
            { row: 5, col: 5 },
            { row: 0, col: 6 },
            { row: 0, col: 7 },
            { row: 1, col: 7 },
            { row: 3, col: 7 },
        ],
    },
    {
        id: "stage-07",
        name: "Stage 07 - Split Route Timing",
        description: "여러 스위치를 눌러 모든 문을 열고 출구로 이동하세요.",
        rows: 8,
        cols: 7,
        maxActions: 55,
        start: { row: 2, col: 0 },
        switches: [
            { group: "A", type: "once", row: 0, col: 1 },
            { group: "B", type: "hold", row: 7, col: 2 },
            { group: "C", type: "hold", row: 2, col: 2 },
            { group: "D", type: "once", row: 0, col: 3 },
        ],
        doors: [
            { group: "A", row: 5, col: 1 },
            { group: "B", row: 5, col: 3 },
            { group: "C", row: 1, col: 5 },
            { group: "D", row: 3, col: 4 },
        ],
        exit: { row: 1, col: 6 },
        walls: [
            { row: 6, col: 0 },
            { row: 7, col: 0 },
            { row: 1, col: 1 },
            { row: 2, col: 1 },
            { row: 3, col: 1 },
            { row: 4, col: 1 },
            { row: 6, col: 1 },
            { row: 7, col: 1 },
            { row: 0, col: 2 },
            { row: 1, col: 2 },
            { row: 3, col: 3 },
            { row: 4, col: 3 },
            { row: 6, col: 3 },
            { row: 7, col: 3 },
            { row: 0, col: 4 },
            { row: 1, col: 4 },
            { row: 2, col: 4 },
            { row: 0, col: 5 },
            { row: 4, col: 5 },
            { row: 5, col: 5 },
            { row: 6, col: 5 },
            { row: 7, col: 5 },
            { row: 0, col: 6 },
            { row: 2, col: 6 },
            { row: 3, col: 6 },
            { row: 4, col: 6 },
            { row: 5, col: 6 },
            { row: 6, col: 6 },
            { row: 7, col: 6 },
        ],
    },
];